### ISSUE TITLE
Add UK.js language file to CKEditor

### ISSUE THREAD

**Issue by VeNick-GS** [GetSimpleCMS-CE/GetSimpleCMS-3.3.19#1]
Hi @risingisland 

I have included Ukrainian language file uk.js in to folder /admin/../ckeditor/lang/. 
File is available in CKE 4.5.9 package https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.5.9/ckeditor_4.5.9_full.zip

When I switch language of the admin panel to Ukrainian then CKEditor toolbar is in English (as default by the configuration) and do not switch to Ukrainian.
How to fix this? Thank you!

**Comment by risingisland** [comment]
Hello @VeNickov 
Let me take a look at this as see why its not working for you.
Do you have a GS and Massive Admin language files? 
Maybe we can bundle these in.

**Comment by risingisland** [comment]
Ah, I see that you do have some lang. files in your fork.
My guess without having looked or tried this out would be that the name of the file needs to be changed.
Everywhere else "ua" is being used.
I am not sure what would be the correct way. I see that several of ckEditor plugins already have "uk" lang files too.
Maybe changing the GS and MA lang files to "uk_UK" would be the easier way.
Only 2 file name changes instead of 20

**Comment by risingisland** [comment]
Either way, let me know. If it is more proper to us "UA", I can rename those files.
@multicolor-rgb and I were just talking about adding in more default langs and how we can build a new community or rebuild the existing.

**Comment by risingisland** [comment]
Good morning @VeNickov
I see you are already testing the lang file name.
Let me know if that was the fix for you.
I think I will add UA to core and change the other file names.
This looks like it is the standard everywhere except ckEditor
If you dont mind, I may be giving you a short list of plugin files to translate?

**Comment by VeNick-GS** [comment]
Hi @risingisland 
I created both lang files ua_UA and uk_UK for GS and for MA plugin.
Also I have created ua.js and uk.js for CKE and CKE plugins. See my fork.
This did not help. More over I receive an error with some plugins ( links etc,) of CKE.

The same issue was discussed on forum http://get-simple.info/forums/showthread.php?tid=9470&pid=59228&highlight=ckeditor+language#pid59228

**Comment by risingisland** [comment]
Wow, quite an ordeal. OK, let me see if I can figure this out today and get back to you.
Thanks for the info.

**Comment by VeNick-GS** [comment]
By the way it would be greate to update CKE to latest version 5. What do you think?

**Comment by risingisland** [comment]
I would love that too. But that will have to wait a little. I have tried upgrading it, but it breaks every time.
This is something that the original team should have done long ago.
Eventually we will get there. Baby steps.

**Comment by VeNick-GS** [comment]
I have tried to update CKE also. But also not succesfull.

**Comment by risingisland** [comment]
In a little while I will send you some updates from Pre to test.

**Comment by risingisland** [comment]
Could you please download Pre and test if UK lang now works?

**Comment by risingisland** [comment]
OK, so, I almost have it working. Both GS base file needed updating an ckEditor is missing about half of its strings.
Let me see if I can find an updated file. If not, I will see if I can pass an um-compressed version to you for translating.

**Comment by risingisland** [comment]
@VeNickov
https://github.com/risingisland/GetSimpleCMS-CE-3.3.19-pre/blob/main/admin/template/js/ckeditor/lang/uk.js
Has been updated, but many string still need to be translated.
It is uncompressed at the moment, so easier to read.
Would you like to translate these, or just update it as is?

**Comment by VeNick-GS** [comment]
Hi @risingisland 
I have download and tested 3.3.19-pre with uk_UK lang. 
CKE with uk.js still doesn't work! I did clean install of your version. 
Other langs are OK.
Also I have translated missing strings in https://github.com/VeNickov/GetSimpleCMS-3.3.19-UA-RU-localization/blob/main/admin/template/js/ckeditor/lang/uk.js

**Comment by risingisland** [comment]
I just did a clean install. A changed several uk files encoding to UTF-8 (not UTF-8-BOM).
I tried it in FF and Chrome. Everything seems to be working fine for me.

**Comment by VeNick-GS** [comment]
Clean install Pre - UK is not working still - EN instead.
Other Langs are OK.

**Comment by VeNick-GS** [comment]
Wow, I have just cleaned cache and UK is visible now!

**Comment by VeNick-GS** [comment]
Did you use my file with UK translation or another one? 
If my then I need to change some words. I will inform you soon

**Comment by VeNick-GS** [comment]
I have updated some UK and RU files. 
Please use these ones:
https://github.com/VeNickov/GetSimpleCMS-3.3.19-UA-RU-localization/blob/main/admin/template/js/ckeditor/lang/ru.js
https://github.com/VeNickov/GetSimpleCMS-3.3.19-UA-RU-localization/blob/main/admin/template/js/ckeditor/lang/uk.js
https://github.com/VeNickov/GetSimpleCMS-3.3.19-UA-RU-localization/blob/main/admin/lang/uk_UK.php 

All files are tested with GS.

**Comment by risingisland** [comment]
The UK file that is being used is the one you provided. Thanks.
I will update these soon and add it to the the new x.19.1 repo.
I am not sure when this will be released or if that version number will change.
But, moving forward, GS will include many base langs by default.

**Comment by risingisland** [comment]
The 3 files have been updated.

From your file, it is important to update this line:
https://github.com/VeNickov/GetSimpleCMS-3.3.19-UA-RU-localization/blob/86d6f6d530264ebebf1b0e2e734b8d629ce12752/admin/lang/uk_UK.php#L327
"en" needs to be changed to "uk"

And although no translation is needed, you should add the section regarding TRANSLITERATION at the bottom of the file.

**Comment by VeNick-GS** [comment]
Hi @risingisland 
Thank you!
I corrected line 327 to "uk" but it was working with "en" also.
Can you give me a link with content of the section TRANSLITERATION? 
I did not find it in the other files.

Also I will continue with ua and ru langs and testing of CE plugins from your repo. I will inform you about.

**Comment by risingisland** [comment]
You can just download this file, it has all of your fixes:
https://github.com/risingisland/GetSimpleCMS-CE-3.3.19.1-pre/blob/main/admin/lang/uk_UK.php#L581

Transliteration starts at line 528

**Comment by VeNick-GS** [comment]
OK, thanks

**Comment by risingisland** [comment]
Also, regarding the plugins. That would be awesome. 
I was just telling multi that I would like to include several if not all langs in those too. 
So anything you are willing to provide would be great. Thanks.

**Comment by risingisland** [comment]
Have you found our Discord channel yet? 
You are welcome there too.
https://discord.gg/26qyU4MF

**Comment by VeNick-GS** [comment]
Joined!

**Comment by WebCrew** [comment]
Wow, what a great discussion about a simple language tag :) 


I just wanted to also add my two cents to the discussion :) and tell you that I think it's great **that you don't let GS-CMS die** - **thank you**. 

Please don't lose your patience and your euphoria, even if hundreds of GitHub "stars" don't end up that quick as a thank you. 

Good luck and continue to enjoy the project.

Regards, Andreas ;)

**Comment by risingisland** [comment]
Thanks for the encouraging words Andreas. 
Nice to know that more than 3 people find our work useful. 😅

**Comment by WebCrew** [comment]
I'm sure there will be more to come over time as the CMS is good and has stood the test of time and now that it's been refreshed word will slowly spreading. 

A tip - register with these magazines which year after year do these surveys and votes "the best Flat File CMS 2023 etc etc" then you will quickly get more traffic and there are masses of these review and rating magazines out there.
