### ISSUE TITLE
CKE Links plugin doesn't work with secure site URL https:// or forced SSL

### ISSUE THREAD

**Issue by VeNick-GS** [GetSimpleCMS-CE/GetSimpleCMS-3.3.19#2]
Hi @risingisland 
One more error with CKE.
GS was installed over non secure URL. In this case no errors with CKE.
When I force SSL in settings of MA or change site ULR to https://.../ or in both cases together then CKE Links pluging does not work.
Errors are:
 
![CKE_Links_plugin_errors](https://github.com/GetSimpleCMS-CE/GetSimpleCMS-3.3.19/assets/78678788/35cc984f-5b89-44ae-8c19-97c195294e32)

**Comment by VeNick-GS** [comment]
Also I installed with secure ULR - the same problem. CKE gives an error with SSL and no error without SSL.
Interesting that it works with CloudFlare redirect to https. In this case no need to force SSL in GS but it need to indicate site URL as https://...

**Comment by multicolor-rgb** [comment]
Hi,
this broken ckeditor, or only show error?

**Comment by VeNick-GS** [comment]
HI @multicolor-rgb 
CKE Links button doesn't work. It is not possible to insert links

**Comment by risingisland** [comment]
Strange, I havent had a problem with it. And its working for me.
In all langs, or just uk?
Edit: uk seems to be working in my Pre version. Did you try to dl the lang files again?
I know I changed several over to UTF-8. BOM seems to cause problems in several langs.

**Comment by VeNick-GS** [comment]
I made several clean installations of 3.3.19 and I have the same problem with Links plugin over https.

**Comment by VeNick-GS** [comment]
Strange, Links plugins is working now with just installed GS 3.3.19.1-pre.
Did you change something?

**Comment by risingisland** [comment]
The only changes were what I had mentioned above. Changing the encoding of several lang files.
Glad this is now working for you.
