### ISSUE TITLE
admin/inc/template_functions.php line 708: utf8_encode is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by redflitzi** [GetSimpleCMS-CE/GetSimpleCMS-3.3.19#3]
In line 708 of template_functions.php:

`	  				$dash .= utf8_encode("\xA0\xA0"); // outer level`

as this is deprecated now, I would suggest replacing it with

`	  				$dash .= "\u{00A0}\u{00A0}"; // outer level`

That syntax will work since PHP 7.0.

**Comment by risingisland** [comment]
Thanks for this find. Its now been added.
